version: "3.8"
services:

  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: on-failure
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './public:/usr/src/app'
      - './docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8000:80'
    depends_on:
      - php


  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8083:8080
    environment:
      SWAGGER_JSON: /app/swagger.json
    volumes:
      - ./swagger.json:/app/swagger.json:ro
volumes:
  db:
